# Generated by Django 4.2.4 on 2023-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CyberSecurityContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeneralContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobUpdatesContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MobilePcContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PythonContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoftwareDevelopmentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UiUxContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(max_length=2000)),
                ("content_name", models.CharField(max_length=100)),
                ("guid", models.CharField(max_length=1000)),
                ("image", models.URLField(max_length=2000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
